### PR TITLE
Fix blogpost chapter nav

### LINKED ISSUE #25: create table of contents navigator for blogposts page

### PR DESCRIPTION
**Pull request by rccsousa**
## Why

With the update to Payload 3.0 and switching to using serialized Lexical nodes instead of `content_html`, blogpost chapter navigation was broken, not allowing to navigate and just displaying different chapter titltes.

## How

By reimplementing chapter navigation using `content_html` and updating Lexical node serialization to include chapter ids on headings.

Closes #25

### CODE REVIEW

File: src/app/_blocks/BlogpostChapters/index.tsx [hunk 1]
```diff
@@ -1,49 +1,59 @@
...
+    root: null,
+    threshold: 0.5,
+  });
+
+  headings.forEach((heading) => observer.observe(heading));
+
+  return () => {
+    headings.forEach((heading) => observer.unobserve(heading));
+  };
+}, [chapters]);
```
Comment (rccsousa) [inline src/app/_blocks/BlogpostChapters/index.tsx:35]: @davelange regarding blogpost chapter nav, IntersectionObserver seems a bit finicky
links are working fine, but the navbar is not working spectacularly. when there is more than 1 id on the viewport" it makes sense, but when there is only one it sometimes work and sometimes doesn't

couldn't find a better way to achieve this result, is there a better way to achieve this result?

demo of the behavior: https://github.com/user-attachments/assets/6c47308a-710a-4103-9a1b-ddc25baf9155

**Review by davelange — APPROVED** [review]
